export const theme = {
  colors: {
    primary: {
      100: "#E6FFF0",
      200: "#B3FFD1",
      300: "#80FFB3",
      400: "#4DFF94",
      500: "#00FF41",
      600: "#00CC34",
      700: "#009926",
    },
    secondary: {
      100: "#FFF3E6",
      200: "#FFD9B3",
      300: "#FFBF80",
      400: "#FFA54D",
      500: "#FF8B1A",
      600: "#E67300",
      700: "#B35900",
    },
    dark: {
      100: "#2A3441",
      200: "#222E3E",
      300: "#1C2530",
      400: "#171E25",
      500: "#141B22",
      600: "#0F1419",
      700: "#0A0E12",
    },
    light: {
      100: "#FFFFFF",
      200: "#F3F4F6",
      300: "#D1D5DB",
      400: "#9CA3AF",
      500: "#6B7280",
      600: "#4B5563",
      700: "#374151",
    },
    status: {
      success: "#00FF41",
      error: "#FF4757",
      warning: "#FF8B1A",
      info: "#00D4FF",
    },
    accent: {
      1: "#00FFD9",
      2: "#00D4FF",
      3: "#B800FF",
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
  },
  borderRadius: {
    none: 0,
    sm: 4,
    md: 8,
    lg: 12,
    xl: 16,
    xxl: 24,
    full: 9999,
  },
} as const;

export const themeComposable = {
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: 700,
      lineHeight: 40,
      letterSpacing: 0.5,
    },
    h2: {
      fontSize: 24,
      fontWeight: 700,
      lineHeight: 32,
      letterSpacing: 0.2,
    },
    body: {
      fontSize: 16,
      fontWeight: 400,
      lineHeight: 24,
      letterSpacing: 0,
    },
    bodyBold: {
      fontSize: 16,
      fontWeight: 700,
      lineHeight: 24,
      letterSpacing: 0.1,
    },
    bodyLarge: {
      fontSize: 18,
      fontWeight: 400,
      lineHeight: 28,
      letterSpacing: 0,
    },
    bodySmall: {
      fontSize: 14,
      fontWeight: 400,
      lineHeight: 20,
      letterSpacing: 0,
    },
  },
  shadows: {
    none: {
      shadowColor: "transparent",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    sm: {
      shadowColor: theme.colors.dark[500],
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3,
      elevation: 2,
    },
    md: {
      shadowColor: theme.colors.dark[500],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    lg: {
      shadowColor: theme.colors.dark[500],
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 8,
    },
    xl: {
      shadowColor: theme.colors.dark[500],
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 12,
    },
    primaryMd: {
      shadowColor: theme.colors.primary[500],
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 8,
    },
    primaryLg: {
      shadowColor: theme.colors.primary[500],
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.7,
      shadowRadius: 16,
      elevation: 8,
    },
    secondaryMd: {
      shadowColor: theme.colors.secondary[500],
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 8,
    },
  },
  textShadows: {
    md: {
      textShadowColor: theme.colors.dark[500],
      textShadowOffset: { width: 0, height: 2 },
      textShadowRadius: 4,
    },
    lg: {
      textShadowColor: theme.colors.dark[500],
      textShadowOffset: { width: 0, height: 3 },
      textShadowRadius: 6,
    },
    primaryMd: {
      textShadowColor: theme.colors.primary[500],
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 8,
    },
    primaryLg: {
      textShadowColor: theme.colors.primary[500],
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 12,
    },
    secondaryMd: {
      textShadowColor: theme.colors.secondary[500],
      textShadowOffset: { width: 0, height: 0 },
      textShadowRadius: 8,
    },
  },
  borders: {
    primaryMd: {
      borderWidth: 2,
      borderRadius: theme.borderRadius.md,
      borderColor: theme.colors.primary[600],
      backgroundColor: theme.colors.dark[300],
    },
  },
} as const;
